routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:adminof-users')->group(function(){
    Route::resource('/users', 'UsersController',['except'=>['show','create','store']]);

});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/sellers', 'ProductsController');

});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:buying-users')->group(function(){
    Route::resource('/carts', 'CartsController');
    Route::resource('/baskets', 'BasketsController');

});

resources/views/admin/sellers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"></div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.sellers.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-2 col-form-label text-md-right">Product</label>

                            <div class="col-md-6">
                                <input id="name" type="name" class="form-control @error('name') is-invalid @enderror" name="name"  required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>



                        <div class="form-group row">
                            <label for="price" class="col-md-2 col-form-label text-md-right">Price</label>

                            <div class="col-md-6">
                                <input id="price" type="price" class="form-control @error('price') is-invalid @enderror" name="price"  required autocomplete="price" autofocus>

                                @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="desc" class="col-md-2 col-form-label text-md-right">Description</label>

                            <div class="col-md-6">
                                <input id="desc" type="desc" class="form-control @error('desc') is-invalid @enderror" name="desc"  required autocomplete="desc" autofocus>

                                @error('desc')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row">
                            <label for="image" class="col-md-2 col-form-label text-md-right">Image</label>
                            <div class="col-md-6">
                            <input type="file" class="form-control-file", id="image", name="image">
        
                            @if ($errors -> has('image'))
                                       <strong>{{ $errors->first('image')}}</strong>
                                       @endif
                                    </div>
                       </div>
                        <button type="submit" class="btn btn-primary">
                            Submit
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/sellers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Product</div>

                <div class="card-body">
                    <form action="{{route('admin.sellers.update',$product)}}" method="POST">
                        {{method_field('PUT')}}
                        @csrf
                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="name" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $product->name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-2 col-form-label text-md-right">Price</label>

                                <div class="col-md-6">
                                    <input id="price" type="price" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ $product->price }}" required autocomplete="price" autofocus>

                                    @error('price')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                     

                            <div class="form-group row">
                                <label for="desc" class="col-md-2 col-form-label text-md-right">Description</label>

                                <div class="col-md-6">
                                    <input id="desc" type="desc" class="form-control @error('desc') is-invalid @enderror" name="desc" value="{{ $product->desc }}" required autocomplete="desc" autofocus>

                                    @error('desc')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>



                       
                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/sellers/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"> <a href="{{route('admin.sellers.create')}}"><button type="button" class="btn btn-success float-left">Add New Product</button></a></div>
                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                  
                            <th scope="col">Product Name</th>
                            <th scope="col">Seller </th>
                            <th scope="col">Image </th>
                            <th scope="col">Actions </th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($products as $product)


                                <tr>
                                    <th scope="row">{{$product->name}}</th>
                                    
                                    <td>{{$product->seller_name}}</td>
                                    <td><img src="/storage/{{$product->image}}" alt="w-100"></td>
                                    <td>
                                        @can('edit-users')
                                            <a href="{{route('admin.sellers.edit',$product->id)}}"><button type="button" class="btn btn-success float-left">Edit</button></a>
                                        @endcan
                                        <form action="{{route('admin.sellers.destroy', $product->id)}}" method="POST" class="float-left">
                                            @csrf
                                            {{method_field('DELETE')}}
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>
                      <span>{!! $products->render() !!}</span>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection