routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:adminof-users')->group(function(){
    Route::resource('/users', 'UsersController',['except'=>['show','create','store']]);

});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/sellers', 'ProductsController');

});

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:buying-users')->group(function(){
    Route::resource('/carts', 'CartsController');
    Route::resource('/baskets', 'BasketsController');

});

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    protected $guarded = [];
    public function users(){
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Admin/CartsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Cart;
use App\Product;
use Illuminate\Http\Request;

class CartsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $products = Product::all();

        //$products =  \DB::table('products')->where('seller_name', 'Admin User');
        return view('admin.carts.index')->with('products',$products);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user,$id, Request $request)
    {
        //add new data 
        //id is the ID of the product 



        $data = $id;
        
        $products = auth()->user()->carts()->create([

            'product' => $data

        ]);

        $products = Product::all();
        $request->session()->flash('success','Product Added to Cart!');
       //return view('admin.carts.index')->with('products',$products);
        return redirect()->route('admin.carts.index');
    }

 
}

resources/views/admin/carts/basket.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">User</div>

                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Roles</th>
                            <th scope="col">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $user)


                                <tr>
                                    <th scope="row">{{$user->id}}</th>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>{{implode('',$user->roles()->get()->pluck('name')->toArray())}}</td>
                                    <td>
                                        @can('edit-users')
                                            <a href="{{route('admin.users.edit',$user->id)}}"><button type="button" class="btn btn-success float-left">Edit</button></a>
                                        @endcan
                                        <form action="{{route('admin.users.destroy', $user)}}" method="POST" class="float-left">
                                            @csrf
                                            {{method_field('DELETE')}}
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/carts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Product Page</div>
                    <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Product Name</th>
                            <th scope="col">Image </th>
                            <th scope="col">Price </th>
                            <th scope="col">Actions </th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($products as $product)


                                <tr>
                                    <th scope="row">{{$product->name}}</th>
                                    <td><img src="/storage/{{$product->image}}" alt="w-100"></td>
                                    <td>{{$product->price}} PHP</td>
                                    <td>
                                        
                                        <a href="{{route('admin.carts.edit',$product->id)}}"><button type="button" name=data class="btn btn-success float-left">Add To Cart</button></a>
                                       @can('manage-users')
                                        <form action="{{route('admin.sellers.store', $product->id)}}" method="POST" class="float-left">
                                            @csrf
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                        @endcan
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>
                      
                </div>
            </div>
        </div>
    </div>
</div>
@endsection